local _, addon = ...

-- Guild names and realms should be lowercase for case insensitivity
addon.communityGuilds = {
	-- Horde
	["huokanbankarea-area52"] = true,
	["huokanbankazralon-azralon"] = true,
	["huokanbankarthas-arthas"] = true,
	["huokanbankbh-bleedinghollow"] = true,
	["huokanbankblackrock-blackrock"] = true,
	["huokan bank barthilas-barthilas"] = true,
	["huokanbankbonechewer-bonechewer"] = true,
	["huokanbankdalaranh-dalaran"] = true,
	["huokanbankfiretree-firetree"] = true,
	["huokanbankfrosth-frostmourne"] = true,
	["huokanbanked-emeralddream"] = true,
	["huokanbankillidan-illidan"] = true,
	["huokanbankhyjal-hyjal"] = true,
	["huokanbankkorgath-korgath"] = true,
	["huokanbankmalganis-mal'ganis"] = true,
	["huokanbankragnaros-ragnaros"] = true,
	["huokanbankstormreaver-stormreaver"] = true,
	["huokanbanktichondrius-tichondrius"] = true,
	["huokanbankthrall-thrall"] = true,
	["huokan bank quelthalas-quel'thalas"] = true,
	["huokan bank zuljin-zul'jin"] = true,
	["huokanbankkj-kil'jaeden"] = true,
	["huokanbankwyrmrest-wyrmrestaccord"] = true,
	["huokan bank durotan-durotan"] = true,
	["huokan bank lightning-lightning'sblade"] = true,
	["huokan bank turalyon-turalyon"] = true,
	["huokan bank nagrandh-nagrand"] = true,
	["huokan bank hagamaggan-agamaggan"] = true,
	["huokan bank andorhal-andorhal"] = true,
	["huokan bank eluneh-elune"] = true,
	["huokan bank boulderfist-boulderfist"] = true,
	["huokan bank nesingwary-nesingwary"] = true,
	-- Alliance
	["huokanbankstormrage-stormrage"] = true,
	["huokanbankblackhand-blackhand"] = true,
	["huokanbankdalarana-dalaran"] = true,
	["huokanbankeda-emeralddream"] = true,
	["huokan bank frosta-frostmourne"] = true,
	["huokanbankproudmoore-proudmoore"] = true,
	["huokanbanknagrand-nagrand"] = true,
	["huokanbankmaga-magtheridon"] = true,
	["huokanbankmoonguard-moonguard"] = true,
	["huokanbanksargeras-sargeras"] = true,
	["huokanbanksilvermoon-silvermoon"] = true,
	["huokanbankscilla-scilla"] = true,
	["huokan bank quelthalasa-quel'thalas"] = true,
	["huokan bank alightbringe-lightbringer"] = true,
	["huokan bank adathremar-dath'remar"] = true,
	["huokan bank akelthuzad-kel'thuzad"] = true,
	["huokan bank ghostlands-ghostlands"] = true,
}
