local _, addon = ...

-- Guild names and realms should be lowercase for case insensitivity
addon.communityGuilds = {
	-- Horde
	["huokanbankarea - area 52"] = true,
	["huokanbankazralon - azralon"] = true,
	["huokanbankarthas - arthas"] = true,
	["huokanbankbh - bleeding hollow"] = true,
	["huokanbankblackrock - blackrock"] = true,
	["huokan bank barthilas - barthilas"] = true,
	["huokanbankbonechewer - bonechewer"] = true,
	["huokanbankdalaranh - dalaran"] = true,
	["huokanbankfiretree - firetree"] = true,
	["huokanbankfrosth - frostmourne"] = true,
	["huokanbanked - emerald dream"] = true,
	["huokanbankillidan - illidan"] = true,
	["huokanbankhyjal - hyjal"] = true,
	["huokanbankkorgath - korgath"] = true,
	["huokanbankmalganis - mal'ganis"] = true,
	["huokanbankragnaros - ragnaros"] = true,
	["huokanbankstormreaver - stormreaver"] = true,
	["huokanbanktichondrius - tichondrius"] = true,
	["huokanbankthrall - thrall"] = true,
	["huokan bank quelthalas - qual'thalas"] = true,
	["huokan bank zuljin - zul'jin"] = true,
	["huokanbankkj - kil'jaeden"] = true,
	["huokanbankwyrmrest - wyrmrest accord"] = true,
	["huokan bank durotan - durotan"] = true,
	-- Alliance
	["huokanbankstormrage - stormrage"] = true,
	["huokanbankblackhand - blackhand"] = true,
	["huokanbankdalarana - dalaran"] = true,
	["huokanbankeda - emerald dream"] = true,
	["huokan bank frosta - frostmourne"] = true,
	["huokanbankproudmoore - proudmoore"] = true,
	["huokanbanknagrand - nagrand"] = true,
	["huokanbankmaga - magtheridon"] = true,
	["huokanbankmoonguard - moon guard"] = true,
	["huokanbanksargeras - sargeras"] = true,
	["huokanbanksilvermoon - silvermoon"] = true,
	["huokanbankscilla - scilla"] = true,
	["huokan bank quelthalasa - quel'thalas"] = true,
}
