local _, addon = ...

-- Guild names and realms should be lowercase for case insensitivity
addon.communityGuilds = {
	-- Horde
	["huokan area - area 52"] = true,
	["huokan bank arthas - arthas"] = true,
	["huokan bank azralon - azralon"] = true,
	["huokan bank barthilas - barthilas"] = true,
	["huokanbank bh - bleeding hollow"] = true,
	["huokan bank boulderfist - boulderfist"] = true,
	["huokan bank bonechewer - bonechewer"] = true,
	["huokan bank dalaran - dalaran"] = true,
	["huokan bank durotan - durotan"] = true,
	["huokan bank draka - draka"] = true,
	["huokan bank earthen ring - earthen ring"] = true,
	["huokan ed h - emerald dream"] = true,
	["huokanbank firetree - firetree"] = true,
	["huokanbank fmh - frostmourne"] = true,
	["huokan bank gurubashi - gurubashi"] = true,
	["huokan bank greymane - greymane"] = true,
	["huokan illidan - illidan"] = true,
	["huokan bank magtheridon - magtheridon"] = true,
	["huokan bank malganis - mal'ganis"] = true,
	["huokan bank nesingwary - nesingwary"] = true,
	["huokanbank stormreaver - stormreaver"] = true,
	["huokan bank tichondrius - tichondrius"] = true,
	["huokan thrall - thrall"] = true,
	["huokanbank hyjal - hyjal"] = true,
	["huokan kj - kil'jaeden"] = true,
	["huokanbank korgath - korgath"] = true,
	["huokan bank kul tiras - kul tiras"] = true,
	["huokan bank lightning - lightning's blade"] = true,
	["huokan bank quelthalas - quel'thalas"] = true,
	["huokan bank rag - ragnaros"] = true,
	["huokan bank silver - silvermoon"] = true,
	["huokan bank turalyon - turalyon"] = true,
	["huokan bank wa - wyrmrest accord"] = true,
	["huokan bank zuljin - zul'jin"] = true,
	-- Alliance
	["huokan bank blackhand - blackhand"] = true,
	["huokan bank adalaran - dalaran"] = true,
	["huokan bank emeralda - emerald dream"] = true,
	["huokan bank proudmoore - proudmoore"] = true,
	["huokan bank frosta - frostmourne"] = true,
	["huokan bank sargeras - sargeras"] = true,
	["huokan bank stormrage - stormrage"] = true,
	["huokan bank moonguard - moonguard"] = true,
	["huokan bank silvermoona - silvermoon"] = true,
	["huokan bank quelthalasa - quel'thalas"] = true,
	["huokan bank nagrand - nagrand"] = true,
}
